CREATE TABLE IF NOT EXISTS tb_parts_api (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_number VARCHAR(50) NOT NULL,
    part_name VARCHAR(100) NOT NULL,
    price NUMERIC (10, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    supplier VARCHAR(100) NOT NULL,
    part_description VARCHAR(500),
    part_created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    part_updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT uq_part_number UNIQUE (part_number),
    CONSTRAINT chk_part_number_upper CHECK (part_number = UPPER(part_number)),
    CONSTRAINT chk_price_positive CHECK (price > 0),
    CONSTRAINT chk_quantity_positive CHECK (quantity > 0)

    );